spring:
  application:
    name: chess-app

  datasource:
    url: jdbc:postgresql://localhost:5432/chessdb
    username: chess
    password: chess

  jpa:
    hibernate:
      ddl-auto: update     # auto-creates/updates tables from our @Entity classes (Module 2)
    show-sql: true          # prints generated SQL to console - handy while learning, turn off later
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970  # hex-encoded 256-bit key, change in production
  expiration-ms: 86400000  # 24 hours