spring:
  application:
    name: chess-app

  datasource:
    url: jdbc:postgresql://localhost:5432/chessdb
    username: chess
    password: chess

  jpa:
    hibernate:
      ddl-auto: update     # auto-creates/updates tables from our @Entity classes (Module 2)
    show-sql: true          # prints generated SQL to console - handy while learning, turn off later
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080